import type { ContentPack, MeasuredMarker, MarkerId } from './types';
import built from './pack.json';

// pack.json is generated by `npm run import-pack`: the evidence thread's pack
// (/mnt/project-files/evidence/) merged with the app's own screen text (app-text.json).
export const pack = built as unknown as ContentPack;

/** A pack counts as signed only with Justina's approval recorded (architect §17.2 item 8). */
export const packSigned = !pack.manifest.placeholder && !!pack.manifest.approved_by && !!pack.manifest.released;

export const markers: MeasuredMarker[] = [...pack.markers].sort((a, b) => a.display_order - b.display_order);
export const markerById = Object.fromEntries(markers.map((m) => [m.id, m])) as Record<MarkerId, MeasuredMarker>;
